name: Build and Deploy React Native App # 워크플로 이름 설정

on:
  push:
    branches:
      - main # main 브랜치에 푸시될 때 실행

env:
  ORG_NAME: 2024-k-html
  PROJECT_NAME: plogging
  SERVICE_NAME: user-app

jobs:
  build-and-deploy: # 잡 이름 설정
    runs-on: ubuntu-latest # Ubuntu 최신 버전에서 실행

    steps:
      - name: Checkout repository # 리포지토리 소스 체크아웃 단계
        uses: actions/checkout@v4 # actions/checkout@v4 액션 사용

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Cache node_modules # node_modules 캐시 단계
        id: cache # 캐시 단계의 ID 설정
        uses: actions/cache@v3 # actions/cache@v3 액션 사용
        with:
          path: '**/node_modules' # 캐시할 경로 설정
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }} # 캐시 키 설정
          restore-keys: |
            ${{ runner.os }}-node- # 복원 키 설정

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/${{ env.ORG_NAME }}/${{ env.PROJECT_NAME }}-${{ env.SERVICE_NAME }}:${{ github.sha }}
            ${{ github.ref == 'refs/heads/main' && format('ghcr.io/{0}/{1}-{2}:latest', env.ORG_NAME, env.PROJECT_NAME, env.SERVICE_NAME) || '' }}
          platforms: linux/amd64 #, linux/arm64/v8